apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
  namespace: argo
spec:
  # invoke the print-message template with "hello world" as the argument to the message parameter
  entrypoint: print-message
  arguments:
    parameters:
      - name: message
        value: hello world

  templates:
    - name: print-message
      inputs:
        parameters:
          - name: message       # parameter declaration
      container:
        # run echo with that message input parameter as args
        image: busybox
        command: [echo]
        args: ["{{inputs.parameters.message}}"]

    - name: print-message-nginx
      inputs:
        parameters:
          - name: message       # parameter declaration
      container:
        # run echo with that message input parameter as args
        image: nginx
        command: [ echo ]
        args: [ "{{inputs.parameters.message}}" ]
